### ISSUE TITLE
null values are not supported

### ISSUE THREAD

**Issue by mgrebenets** [wollardj/simple-plist#61]
Trying to write a simple JSON with a `null` value fails in underlying `bplist-creator` package.

```json
{
  "key": null
}
```

Yes, `null` value is as good as nothing, but there's nothing wrong with having it in a JSON overall.
While for our use case, we can sanitize the JSON by removing `null`s before creating plist, overall I think the library should be able to write and read null values for properties.

> TypeError: Cannot read property 'bplistOverride' of null
    at toEntries (/path/packages/build/node_modules/simple-plist/node_modules/bplist-creator/bplistCreator.js:320:13)
    at /path/packages/build/node_modules/simple-plist/node_modules/bplist-creator/bplistCreator.js:419:22
    at Array.forEach (<anonymous>)
    at toEntriesObject (/path/packages/build/node_modules/simple-plist/node_modules/bplist-creator/bplistCreator.js:418:21)
    at toEntries (/path/packages/build/node_modules/simple-plist/node_modules/bplist-creator/bplistCreator.js:356:14)
    at /path/packages/build/node_modules/simple-plist/node_modules/bplist-creator/bplistCreator.js:419:22
    at Array.forEach (<anonymous>)
    at toEntriesObject (/path/packages/build/node_modules/simple-plist/node_modules/bplist-creator/bplistCreator.js:418:21)
    at toEntries (/path/packages/build/node_modules/simple-plist/node_modules/bplist-creator/bplistCreator.js:356:14)
    at module.exports (/path/packages/build/node_modules/simple-plist/node_modules/bplist-creator/bplistCreator.js:26:17)

**Comment by wollardj** [comment]
I agree that there is a difference between a key that has been set to 'nothing' vs the concept of 'nothing at all' (sans a corresponding key). But, that package isn't controlled by me. If you can move this issue over to https://github.com/joeferner/node-bplist-creator/issues and get a change into that project, I'll gladly update that dependency and release a new version.

**Comment by wollardj** [comment]
I'm going to close this one because the plist spec doesn't have a place for `null` values.

* https://en.wikipedia.org/wiki/Property_list
* https://www.apple.com/DTDs/PropertyList-1.0.dtd
